#!/bin/bash

# Our settings

#Let's make sure the environment is clean and ready to compile the kernel
echo
echo "Cleaning house!!"
echo
rm -rf ../final_files/dt.img
rm -rf ../final_files/zImage
rm -rf ../final_files/boot.img

echo
echo "House cleaned, lets build a kernel!!!"
echo
#
# Lets set the kernel defconfig
#
# Let's build a kernel
echo
echo "Now compiling kernel, go get a soda! ;)"
echo
ARCH=arm CROSS_COMPILE=~/android_prebuilt_toolchains/arm-cortex_a15-linux-gnueabihf-linaro_4.9.1/bin/arm-cortex_a15-linux-gnueabihf- make CONFIG_DEBUG_SECTION_MISMATCH=y -j8
#
echo "checking for compiled kernel..."
if [ -f arch/arm/boot/zImage ]
then
	  echo
      echo "Togari has been compiled!!! You can find it in arch/arm/boot/zImage"
	  echo
else
      echo
	  echo "Kernel did not compile, please check for errors!!"
	  echo
fi

echo "generating device tree..."
./dtbTool -o ../final_files/dt.img -s 2048 -p ./scripts/dtc/ ./arch/arm/boot/

# These move files to easier locations

cp arch/arm/boot/zImage ../final_files/zImage

# This part packs the img up :)
#
cd ..
#
echo "Now packing boot.img"
#
cd ~/ZUltra/final_files/
#
./mkbootimg --base 0x00000000 --kernel zImage --ramdisk_offset 0x02000000 --tags_offset 0x01E00000 --pagesize 2048 --cmdline "androidboot.hardware=qcom user_debug=31 maxcpus=2 msm_rtb.filter=0x3F ehci-hcd.park=3 msm_rtb.enable=0 lpj=192598 dwc3.maximum_speed=high dwc3_msm.prop_chg_detect=Y" --ramdisk newramdisk.cpio.gz --dt dt.img -o boot.img
#
#
if [ -f /home/jazz/ZUltra/final_files/boot.img ]; then
	  echo
      echo "Successful Building Boot Image for Togari"
	  echo
else
      echo
	  echo "Kernel did not compile, please check for errors!!"
	  echo
fi

echo "Connect phone via USB Cable"
#
#
adb devices
sleep 5
#
#
echo "adb device detected"
sleep 5
#
echo "rebooting to booloader"
#
adb reboot bootloader
sleep 5
#
#
echo "flashing boot image"
sleep 5
#
fastboot flash boot ~/ZUltra/final_files/boot.img
sleep 5
#
#
fastboot reboot
#
echo "flashing os boot image successful!!!"

adb kill-server

cd ../kernel1/
